package com.example.photooftheday.model.recycler

data class DataRecycler (
    val id: Int,
    val titlePOD: String,
    val descriptionPOD: String,
    val like: Boolean
)

fun getPhotoPODData() : List<DataRecycler> {
    return listOf(
        DataRecycler(0,"Фото дня", "", false),
        DataRecycler(1,"Apollo 17: The Crescent Earth", "Our fair planet sports a curved, sunlit crescent against the black backdrop of space in this stunning photograph. From the unfamiliar perspective, the Earth is small and, like a telescopic image of a distant planet, the entire horizon is completely within the field of view. Enjoyed by crews on board the International Space Station, only much closer views of the planet are possible from low Earth orbit. Orbiting the planet once every 90 minutes, a spectacle of clouds, oceans, and continents scrolls beneath them with the partial arc of the planet's edge in the distance. But this digitally restored image presents a view so far only achieved by 24 humans, Apollo astronauts who traveled to the Moon and back again between 1968 and 1972. The original photograph, AS17-152-23420, was taken by the homeward bound crew of Apollo 17, on December 17, 1972. For now it's the last picture of Earth from this planetary perspective taken by human hands.   - NASA Remembers Michael Collins -", false),
        DataRecycler(2,"Perseverance from Ingenuity", "Flying at an altitude of 5 meters (just over 16 feet), on April 25 the Ingenuity helicopter snapped this sharp image. On its second flight above the surface of Mars, its color camera was looking back toward Ingenuity's current base at Wright Brothers Field and Octavia E. Butler Landing marked by the tracks of the Perseverance rover at the top of the frame. Perseverance itself looks on from the upper left corner about 85 meters away. Tips of Ingenuity's landing legs just peek over the left and right edges of the camera's field of view. Its record setting fourth flight completed on April 30, Ingenuity collected images of a potential new landing zone before returning to Wright Brothers Field. Ingenuity's fifth flight would be one-way though as the Mars aircraft moves on to the new airfield, anticipating a new phase of operational demonstration flights.", false),
        DataRecycler(3,"Clouds of the Carina Nebula", "What forms lurk in the mists of the Carina Nebula? The dark ominous figures are actually molecular clouds, knots of molecular gas and dust so thick they have become opaque.  In comparison, however,  these clouds are typically much less dense than Earth's atmosphere.  Featured here is a detailed image of the core of the Carina Nebula, a part where both dark and colorful clouds of gas and dust are particularly prominent.  The image was captured in mid-2016 from Siding Spring Observatory in Australia.  Although the nebula is predominantly composed of hydrogen gas -- here colored green, the image was assigned colors so that light emitted by trace amounts of sulfur and oxygen appear red and blue, respectively.  The entire Carina Nebula, cataloged as NGC 3372, spans over 300 light years and lies about 7,500 light-years away in the constellation of Carina. Eta Carinae, the most energetic star in the nebula, was one of the brightest stars in the sky in the 1830s, but then faded dramatically.", false),
        DataRecycler(4,"Apollo 11: Earth, Moon, Spaceship", "After the most famous voyage of modern times, it was time to go home. After proving that humanity has the ability to go beyond the confines of planet Earth, the first humans to walk on another world -- Neil Armstrong and Buzz Aldrin -- flew the ascent stage of their Lunar Module back to meet Michael Collins in the moon-orbiting Command and Service Module. Pictured here on 1969 July 21 and recently digitally restored, the ascending spaceship was captured by Collins making its approach, with the Moon below, and Earth far in the distance.  The smooth, dark area on the lunar surface is Mare Smythii located just below the equator on the extreme eastern edge of the Moon's near side.  It is said of this iconic image that every person but one was in front of the camera.   - NASA Remembers Michael Collins -",false),
        DataRecycler(5,"Space Station, Solar Prominences, Sun", "That's no sunspot. It's the International Space Station (ISS) caught passing in front of the Sun. Sunspots, individually, have a dark central umbra, a lighter surrounding penumbra, and no Dragon capsules attached.  By contrast, the ISS is a complex and multi-spired mechanism, one of the largest and most complicated spacecraft ever created by humanity.  Also, sunspots circle the Sun, whereas the ISS orbits the Earth.  Transiting the Sun is not very unusual for the ISS, which orbits the Earth about every 90 minutes, but getting one's location, timing and equipment just right for a great image is rare.  The featured picture combined three images all taken from the same location and at nearly the same time. One image -- overexposed -- captured the faint prominences seen across the top of the Sun, a second image -- underexposed -- captured the complex texture of the Sun's chromosphere, while the third image -- the hardest to get -- captured the space station as it shot across the Sun in a fraction of a second.  Close inspection of the space station's silhouette even reveals a docked Dragon Crew capsule.",false)
    )
}